### PR TITLE
Added get_server_data and check_profile poly methods

### PR DESCRIPTION
**Pull request by jimboca**
Let me know what you guys think.  I have similar code in most of my nodeservers and get tired of duplicating the code.

### CODE REVIEW

**Comment by jimboca** [comment]
This also allows the nodeserver to print its version on startup https://github.com/Einstein42/udi-poly-template-python/blob/4677521a9b7aff1488218964962c8bc4867a66c5/template-poly.py#L83

**Review by Einstein42 — APPROVED** [review]

**Comment by jimboca** [comment]
@exking You good with this?  I'd like to get it released if you all like it.

**Review by exking — APPROVED** [review]
Looks good, thanks!

**Comment by jimboca** [comment]
Thanks guys, all merged @Einstein42 please release.

**Pull request merged**
