### PR TITLE
Add set_basic_config method

### PR DESCRIPTION
**Pull request by jimboca**
Add set_basic_config method, and get_server_data check_profile=None option to force profile reloads on every restart when testing.

### CODE REVIEW

**Review by simplextech — APPROVED** [review]
Seems good but I haven't done any testing yet.

**Review by bpaauwe — COMMENTED** [review]
The changes look good.  I really like the force profile load option, that seems pretty handy.  I have basically 2 general comments.

1) This really is two separate changes so it would be good if they were also two separate commits.  Keeping the commits separate can make it a lot easier to debug issues in the future. I don't see any dependencies between the two features.

2) As I've said before, I'd like to see better commit messages.  I work on an open source project that uses very verbose commit messages as part of my day job. Having good descriptions of what each commit is doing really helps when looking at unfamiliar code. 

Here's what I think the commit message for the first change would look like.  This is also a good test to see if I understood what the change is doing.

Add flag to server.json to enable always uploading profile files on startup

Add check_profile=None in the server.json file to force the uploading of the
profile files when the node server is started. This will ignore the normal 
profile version checks.

**Comment by jimboca** [comment]
@bpaauwe I agree about the commit messages, but I got annoyed with testing profile changes while working on the current changes and testing with template node server and the changes were intermixed in the same code, so that's why it all happened at once.  I'm not great at commit messages and I will try to improve in the future :)

Also, it's not a server.json setting, it's a argument to the get_server_data and check_profile methods. which reference the profile_version setting in server.json.  But, it's a good idea to set profile_version to something that would force a reload on each restart as well...  And yes, the get_server_data and check_profile don't work with pgc_interface, I will try to find spare time to add them there since I could use them on Ecobee NS...

**Comment by bpaauwe** [comment]
> @bpaauwe I agree about the commit messages, but I got annoyed with testing profile changes while working on the current changes and testing with template node server and the changes were intermixed in the same code, so that's why it all happened at once. I'm not great at commit messages and I will try to improve in the future :)

Yeah, I understand. I do that quite a bit too. If it's just a one line fix, I'll commit it with the change, but I do try to make commits that are independent.  It's pretty easy when the changes are in different files.  

I'll do a git status to see what files I've changed
then I'll do a git diff on each to see what I changed in each and try to mentally assign what goes in each commit.  

Sometimes there are multiple changes in a single file that should be in separate commits. GIT makes that pretty easy to do too as you can do a git add -p and it will ask you if you want to stage the commit or not. So 
git add -p file
git commit file(s)

In some cases, if I've spent a bunch of time making a lot of different modifications I'll just commit stuff to get it in the repository and then go back and edit/split and move around commits to make the commit sequence make sense.  That's quite a bit of work.

> Also, it's not a server.json setting, it's a argument to the get_server_data and check_profile methods. which reference the profile_version setting in server.json. But, it's a good idea to set profile_version to something that would force a reload on each restart as well... 

Ahh, so I didn't quite understand how it worked.  So does that mean you have to remove the argument (or change it's value) before releasing the code?

**Comment by jimboca** [comment]
> Ahh, so I didn't quite understand how it worked. So does that mean you have to remove the argument (or change it's value) before releasing the code?

Yes, typically it's True to check that the profile version recorded in the DB is the same as the version in server.json, but when testing I end up editing the server.json before each restart to force a new verison, so instead I can now just set it to None, but yes, I have to remember to set it back to True before releasing or once my changes are working.

**Review by exking — APPROVED** [review]

**Comment by exking** [comment]
@jimboca why do you re-request the review? I don't see new commits?

**Comment by jimboca** [comment]
> @jimboca why do you re-request the review? I don't see new commits?

@exking Sorry, not sure how that happened, I went to add someone else but wasn't able to, not sure why it added you again.

**Comment by bpaauwe** [comment]
> > Ahh, so I didn't quite understand how it worked. So does that mean you have to remove the argument (or change it's value) before releasing the code?
> 
> Yes, typically it's True to check that the profile version recorded in the DB is the same as the version in server.json, but when testing I end up editing the server.json before each restart to force a new verison, so instead I can now just set it to None, but yes, I have to remember to set it back to True before releasing or once my changes are working.

I guess I need to review how the profile versioning works more closely.  I understand now, and I'm cool with modifying the server.json's profile version to None to invoke this.  I'm far less likely to push that change then something I'd have to change in the controller's source file. 

I typically modify the server.json with the versions and the README.md with the version change log as the last commit I do before releasing with a simple commit message of "Version x.x.x". That way when I look at the git log, I see each release version clearly.  This also means that using this feature only adds a very minor addition to my normal work flow, so that's great.  Thanks for making this change.

**Review by bpaauwe — APPROVED** [review]
Approved with caveats.

I'd really like us (all of us) to be a bit more disciplined when creating commits.  In general features should be separate commits, commit messages should explain the "why" for the change and we should really make sure all of the (3?) interfaces get the same features concurrently.

**Comment by jimboca** [comment]
To force profile load, would you all prefer in the json:
    "profile_version": null,
or
    "profile_version": "",
or
    "profile_version": "None",
or what?

The json null converts to a None in python when reading the json, so that's my preference... Just wish we could put comments in json :(

**Review by bpaauwe — APPROVED** [review]
Looks good

**Comment by bpaauwe** [comment]
> To force profile load, would you all prefer in the json:
> "profile_version": null,
> or
> "profile_version": "",
> or
> "profile_version": "None",
> or what?
> 
> The json null converts to a None in python when reading the json, so that's my preference... Just wish we could put comments in json :(

I agree, null seems to be what json typically uses for cases like this.

**Pull request merged**
