### PR TITLE
New PolyInterface class

### PR DESCRIPTION
**Pull request by brettahale**
Change the behavior so the module wouldn't auto initialize. Allows for easier testability for Node Server projects.
Requires you to change the Node Server main functionality.
```
#!/usr/bin/env python
import sys
from poly_interface import LOGGER, PolyInterface, Interface
from nuvo_controller import Controller
if __name__ == "__main__":

    polyinterface = PolyInterface()
    polyglot = Interface('Example NodeServer')

    try:
        polyglot.start()
        control = Controller(polyglot)
        control.runForever()
    except (KeyboardInterrupt, SystemExit):
        polyglot.stop()
        sys.exit(0)
```

### CODE REVIEW

**Comment by jimboca** [comment]
@brettahale We can't possibly change every nodeserver to be compatible at the same time with this change?

**Comment by brettahale** [comment]
It would just be a matter of which version of poly-interface people use to build nodeservers right? If they wanted to upgrade to the next version of polyglot-v2-python-interface, they would have to account for these breaking changes. Unless I'm missing something, which is very possible :)

**Comment by jimboca** [comment]
Yes, when one nodeserver upgrades then all other nodeservers running on that polyglot instance would also have to support the new one which will be very painful.  Sounds like what you have done is good, but just not sure how we can roll it out.  Need @Einstein42 to chime in...

**Comment by brettahale** [comment]
Oh gotcha, good call!

**Comment by Einstein42** [comment]
Breaking changes = bad. Find a way to do it without breaking.

**Pull request closed without merging**
